# Generated by Django 3.2.13 on 2022-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=120)),
                ('style', models.CharField(max_length=120)),
                ('painter', models.CharField(max_length=120)),
                ('yearofcreation', models.CharField(max_length=4)),
                ('artdescription', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Arts',
            },
        ),
    ]
